config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'
  get 'password_resets/edit'

  get 'page_not_found_error/not_found'
  get 'store/index'
  get 'users/new'
  get 'charts/sports_chart'
  get 'charts/pie_chart_form'
  get 'charts/hosts_chart'
  get 'charts/column_chart_form'
  
  root 'static_pages#home'

  get '/barchart', to: 'charts#medals_chart'
  get '/columncharts', to: 'charts#events_chart'
  get '/facebook', to: 'facebook#index'
  get '/store', to: 'store#index'
  get '/cart', to: 'carts#index'
  get '/about', to: 'static_pages#about'
  get '/home', to: 'static_pages#home'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  delete '/cart.:id', to: 'carts#destroy'
  
  resources :results
  resources :hosts
  resources :sports
  resources :athletes
  resources :users
  resources :products
  resources :orders
  resources :line_items
  resources :carts
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  match '*a', :to => 'page_not_found_error#not_found', via: :get
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :host
  belongs_to :sport
  belongs_to :athlete


  def full_name 
    [athlete_surname, athlete_forename].join(' ')
  end     

  def self.pie_chart
  	Result.includes(:athlete).includes(:sport).group('athlete_id', 'athlete_surname').where("medal = 'Gold' OR medal = 'Silver' OR medal = 'Bronze'").order("count(medal) desc").limit(5).pluck("athlete_surname, count(medal) as medals_number")
  end	

  def self.column_chart
  	Result.includes(:athlete).includes(:host).group('athlete_id', 'athlete_surname').where("medal = 'Gold' OR medal = 'Silver' OR medal = 'Bronze'").order("count(medal) desc").limit(5).pluck("athlete_surname, count(medal) as medals_number")
  end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :set_result, only: [:show, :edit, :update, :destroy]

  # GET /results
  # GET /results.json
  def index
    @results = Result.all
  end

  # GET /results/1
  # GET /results/1.json
  def show
  end

  # GET /results/new
  def new
    @result = Result.new
  end

  # GET /results/1/edit
  def edit
  end

  # POST /results
  # POST /results.json
  def create
    @result = Result.new(result_params)

    respond_to do |format|
      if @result.save
        format.html { redirect_to @result, notice: 'Result was successfully created.' }
        format.json { render :show, status: :created, location: @result }
      else
        format.html { render :new }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /results/1
  # PATCH/PUT /results/1.json
  def update
    respond_to do |format|
      if @result.update(result_params)
        format.html { redirect_to @result, notice: 'Result was successfully updated.' }
        format.json { render :show, status: :ok, location: @result }
      else
        format.html { render :edit }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @result.destroy
    respond_to do |format|
      format.html { redirect_to results_url, notice: 'Result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def result_params
      params.require(:result).permit(:host_id, :sport_id, :athlete_forename, :athlete_surname, :country, :gender, :event, :medal)
    end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_form.html.erb
<%= form_with(model: result, local: true) do |form| %>
  <% if result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :host_id %>
    <%= form.number_field :host_id, id: :result_host_id %>
  </div>

  <div class="field">
    <%= form.label :sport_id %>
    <%= form.number_field :sport_id, id: :result_sport_id %>
  </div>

  <div class="field">
    <%= form.label :athlete_forename %>
    <%= form.text_field :athlete_forename, id: :result_athlete_forename %>
  </div>

  <div class="field">
    <%= form.label :athlete_surname %>
    <%= form.text_field :athlete_surname, id: :result_athlete_surname %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country, id: :result_country %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender, id: :result_gender %>
  </div>

  <div class="field">
    <%= form.label :event %>
    <%= form.text_field :event, id: :result_event %>
  </div>

  <div class="field">
    <%= form.label :medal %>
    <%= form.text_field :medal, id: :result_medal %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/results/edit.html.erb
<h1>Editing Result</h1>

<%= render 'form', result: @result %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

app/views/results/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Results</h1>

<table>
  <thead>
    <tr>
      <th>Host id</th>
      <th>Sport id</th>
      <th>Athlete id</th>
      <th>Event</th>
      <th>Medal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |result| %>
      <tr>
        <td><%= result.host_id %></td>
        <td><%= result.sport_id %></td>
        <td><%= result.athlete_id %></td>
        <td><%= result.event %></td>
        <td><%= result.medal %></td>
        <td><%= link_to 'Show', result %></td>
        <td><%= link_to 'Edit', edit_result_path(result) %></td>
        <td><%= link_to 'Destroy', result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Result', new_result_path %>

app/views/results/new.html.erb
<h1>New Result</h1>

<%= render 'form', result: @result %>

<%= link_to 'Back', results_path %>

app/views/results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Host:</strong>
  <%= @result.host_id %>
</p>

<p>
  <strong>Sport:</strong>
  <%= @result.sport_id %>
</p>

<p>
  <strong>Athlete forename:</strong>
  <%= @result.athlete_forename %>
</p>

<p>
  <strong>Athlete surname:</strong>
  <%= @result.athlete_surname %>
</p>

<p>
  <strong>Country:</strong>
  <%= @result.country %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @result.gender %>
</p>

<p>
  <strong>Event:</strong>
  <%= @result.event %>
</p>

<p>
  <strong>Medal:</strong>
  <%= @result.medal %>
</p>

<%= link_to 'Edit', edit_result_path(@result) %> |
<%= link_to 'Back', results_path %>